name: build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install clang
        run: sudo apt-get update && sudo apt-get install clang-10

      - name: Compile tests
        run: |
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DBITIO_DEVEL=ON .
          make bitio_test

      - name: Run tests
        run: bin/bitio_test
